### ISSUE TITLE
Incorrect model for IPAM config settings

### ISSUE THREAD

**Issue by Mossop** [fussybeaver/bollard#201]
The current model for IPAM configuration is incorrect. It currently (https://cs.github.com/fussybeaver/bollard/blob/5effe1a16363d929e290919bca6542bbfaccd45a/codegen/target/generated-sources/src/models.rs#L1991) assumes a map of string keys to string values but the values can be more complex than this. One such example is the AuxiliaryAddresses setting which rather than having a string value is actually a map of strings to addresses.

One of my servers is using this, the list networks API call returns the following for the network in question:
```json
{
    "Name": "services",
    "Id": "18e9cdac5d71b5b050b804b6d9d07aaa4104a986bf478e89057a088724c6328e",
    "Created": "2022-02-19T16:14:03.323536217Z",
    "Scope": "local",
    "Driver": "macvlan",
    "EnableIPv6": false,
    "IPAM": {
      "Driver": "default",
      "Options": null,
      "Config": [
        {
          "Subnet": "10.10.0.0/20",
          "IPRange": "10.10.12.0/24",
          "Gateway": "10.10.15.254",
          "AuxiliaryAddresses": { "bad": "10.10.12.0", "host": "10.10.12.1" }
        }
      ]
    },
    "Internal": false,
    "Attachable": true,
    "Ingress": false,
    "ConfigFrom": { "Network": "" },
    "ConfigOnly": false,
    "Containers": {},
    "Options": {
      "com.docker.network.bridge.name": "services",
      "parent": "enp1s0"
    },
    "Labels": {
      "com.docker.compose.network": "services",
      "com.docker.compose.project": "srv",
      "com.docker.compose.version": "1.24.1"
    }
  }
```

Bollard returns an error on encountering this due to the incorrect model: `Failed to deserialize JSON: invalid type: map, expected a string at line 1 column 1057`.

**Comment by Mossop** [comment]
Looks like the swagger definition is incorrect here so that's unhelpful!

```yaml
  IPAM:
    type: "object"
    properties:
      Driver:
        description: "Name of the IPAM driver to use."
        type: "string"
        default: "default"
      Config:
        description: |
          List of IPAM configuration options, specified as a map:

          ```
          {"Subnet": <CIDR>, "IPRange": <CIDR>, "Gateway": <IP address>, "AuxAddress": <device_name:IP address>}
          ```
        type: "array"
        items:
          type: "object"
          additionalProperties:
            type: "string"
      Options:
        description: "Driver-specific options, specified as a map."
        type: "object"
        additionalProperties:
          type: "string"
```
