### ISSUE TITLE
Docker pull images

### ISSUE THREAD

**Issue by soucosmo** [fussybeaver/bollard#455]
What would the code snippet for the equivalent of docker pull look like?

Example: docker pull ubuntu:23.04, I didn't find anything in the docs that makes sense for this.

**Comment by kanpov** [comment]
It seems like pulling images is actually completely missing, which is strange to say the least.

**Comment by x1a0b0** [comment]
> What would the code snippet for the equivalent of docker pull look like?
> 
> Example: docker pull ubuntu:23.04, I didn't find anything in the docs that makes sense for this.

take a look at https://docs.docker.com/engine/api/v1.46/#tag/Image/operation/ImageCreate
corresponding method is https://github.com/fussybeaver/bollard/blob/master/src/image.rs#L618

**Comment by soucosmo** [comment]
The example not working for me.

# main.rs
```rust
use bollard::image::CreateImageOptions;
use futures_util::TryStreamExt;
use std::default::Default;
use bollard::Docker;


#[tokio::main]
async fn main() {
    
    let docker = Docker::connect_with_http_defaults().unwrap();


    let options = Some(CreateImageOptions{
        from_image: "hello-world",
        ..Default::default()
    });


    docker.create_image(options, None, None);
    
}
```

# Cargo.toml
```toml
[package]
name = "teste-docker"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.17.1"
futures-util = "0.3.30"
tokio = { version = "1.38", features = ["fs", "rt-multi-thread", "macros"] }

```

The method to create container works normally.
